### ISSUE TITLE
Use CCache to speedup recompilation

### ISSUE THREAD

**Issue by PhilippvK** [tum-ei-eda/seal5#115]
We can heavily reduce compilation times locally and in CI by utilizing CCache

- [x] Support CCache in Seal5 Flow
- [x] Expose CCache to CommandLine/Python
- [x] Update Examples to optionally use CCache
- [x] Use CCache in CI

**Comment by PhilippvK** [comment]
Implemented on `develop`.

Runtime for demo on CI can be reduced from 90 minutes to 15 minutes (assuming that the cache already exists)

@kebi-be This might also be interesting for the CI Flow you are working on. I am happy to show you the required patches to enable CCache.

**Comment by thomasgoodfellow** [comment]
Very interesting news! I tried CCache once with under-impressive results, but not recently. Do you have any info/feel for how the benefit changes with the scale of source change? (e.g. change a header that triggers recompilation of X% of the objects, CCache takes Y% of the normal time)?

**Comment by kebi-be** [comment]
Sure. I will be glad to have this integrated in the CI to speed-up build. Let me know which patches I need to enable the CCache.

**Comment by PhilippvK** [comment]
> Sure. I will be glad to have this integrated in the CI to speed-up build. Let me know which patches I need to enable the CCache.

@kebi-be Her are the relevant CI snippets from https://github.com/tum-ei-eda/seal5/blob/develop/.github/workflows/demo.yml

```
- name: Setup ccache
      if: ${{ matrix.ccache == '1' }}
      uses: hendrikmuhs/ccache-action@v1
      with:
        max-size: 2G
        key: ${{ matrix.os }}-${{ github.event.inputs.script }}-${{ github.event.inputs.build_config }}
        variant: sccache
...
    - name: Run the demo
      run: |
        source .venv/bin/activate
        VERBOSE=${{ github.event.inputs.verbose }} PROGRESS=${{ github.event.inputs.progress }} CCACHE=${{ matrix.ccache }} CLONE_DEPTH=${{ github.event.inputs.clone_depth }} BUILD_CONFIG=${{ github.event.inputs.build_config }} IGNORE_ERROR=${{ github.event.inputs.ignore_error }} TEST=${{ github.event.inputs.test }} INSTALL=${{ github.event.inputs.install }} DEPLOY=${{ github.event.inputs.deploy }} EXPORT=${{ github.event.inputs.export }} DEST=/tmp/seal5_llvm ${{ steps.ctx.outputs.program }} examples/${{ github.event.inputs.script }}
```

The examples should all expose the `CCACHE` environment variable which was added here:

https://github.com/tum-ei-eda/seal5/commit/2cd3502cb4e48febd70f0b226e1519efc36e8db0#diff-49f22250669239911383a3046c0f33ebda0c04a05b6a282fdd22fedd0bbb8acb

Alternatively, the feature can be enabled via the settings `llvm.ccache: true`. But I do not want to alter the default here as it would break the the required OS packages are missing.

The patches are still on `develop` but I will merge develop into main soon to prepare a new Release.
