### ISSUE TITLE
Write number of changed files/lines per patch/stage to metrics

### ISSUE THREAD

**Issue by PhilippvK** [tum-ei-eda/seal5#138]
This would allow us to give a summary of LOCs (lines of code) generated/modified by Seal5.

**Comment by PhilippvK** [comment]
I have added a quick PoC via 32db47c2ae81f985755c38ba2253c53e95befc72 & d7f85cdda10e5ac029276a07e61c3e619062ebc5 which can generate the following data:

```yaml
# cat /tmp/settings.yml
---
...
metrics:
...
- patch:
    stages:
      PHASE_1:
        n_deletions: 0
        n_files_changed: 7
        n_insertions: 28
      PHASE_2:
        n_deletions: 0
        n_files_changed: 41
        n_insertions: 1683
...
- patch:
    stages:
      PHASE_3:
        n_deletions: 0
        n_files_changed: 0
        n_insertions: 0
      PHASE_4:
        n_deletions: 0
        n_files_changed: 38
        n_insertions: 407
      PHASE_5:
        n_deletions: 0
        n_files_changed: 0
        n_insertions: 0
...
- deploy:
    n_deletions: 0
    n_files_changed: 84
    n_insertions: 2118
...
```
